from space_utils.addtree_cs_vgg16 import build_tree as build_tree_vgg16
from space_utils.addtree_cs_vgg16 import path2funcparam as path2funcparam_vgg16

from space_utils.addtree_cs_resnet50 import build_tree as build_tree_resnet50
from space_utils.addtree_cs_resnet50 import path2funcparam as path2funcparam_resnet50
