from space_utils.addtree_cs_vgg16 import build_tree as build_tree_vgg16
from space_utils.addtree_cs_vgg16 import path2funcparam as path2funcparam_vgg16

# resnet 50
from space_utils.addtree_cs_resnet50 import build_tree as build_tree_resnet50
from space_utils.addtree_cs_resnet50 import path2funcparam as path2funcparam_resnet50

# resnet56
from space_utils.addtree_cs_resnet56 import build_tree as build_tree_resnet56
from space_utils.addtree_cs_resnet56 import path2funcparam as path2funcparam_resnet56

# jenatton small
from space_utils.addtree_cs_jenatton_small import build_tree as build_tree_jenatton_small
from space_utils.addtree_cs_jenatton_small import path2funcparam as path2funcparam_jenatton_small

# resnet20 NAS
from space_utils.addtree_cs_resnet20_nas import build_tree as build_tree_resnet20_nas
from space_utils.addtree_cs_resnet20_nas import path2funcparam as path2funcparam_resnet20_nas

